### ISSUE TITLE
Unable to append one node to another

### ISSUE THREAD

**Issue by ispringle** [Shinmera/lquery#19]
I've been fighting this for about a week now and am totally lost/unsure what I'm doing wrong. The following is enough to get the issue I'm seeing:
```lisp
(defparameter *dom* (lquery:$ (initialize #p"www/index.html")))
(defparameter *head* (lquery:$ (initialize #p"www/elements/head.html")))
(lquery:$ *dom* "head" (append *head*) (write-to-file #p"out/index.html")
```

Where `index.html` can be as simple as:
```html
<html>
<head></head>
</html>
```

And `head.html` can be:
```html
<title>I should get templated into "index.html"</title>
```

When I try to run the above I get the error:
```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION (COMMON-LISP:SETF PLUMP-DOM:PARENT) (1)>
when called with arguments
  (#<PLUMP-DOM:ELEMENT head {7007E6D563}>
   #<PLUMP-DOM:ROOT {7007F8EC63}>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
```

Based on the [docs](https://shinmera.github.io/lquery/#FUNCTION%20LQUERY-FUNCS%3AAPPEND), I assume this should work since takes a node and then html or nodes. I was able to sort of get this working by converting the `*head*` into a string with `serialize` but that was giving me a number of other issues.

**Comment by Shinmera** [comment]
the value of *head* is of type `root`, which is not an element that can be appended.

what you want is the elements within the root, so use `lquery:$1` in your defparameter, or extract the element you want in your `append`.

**Comment by ispringle** [comment]
Ah, that makes sense. Thanks for explaining, that did the trick!
