### ISSUE TITLE
Does not build - SBCL type assertion failure

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/lquery#2]
Here's the log, I can't quite puzzle it out:

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/lquery/9f2f17651b09be86e109302744f092c81bc9b08c/lquery-20150110-git/toolkit.lisp
    ; in: DEFGENERIC NODES-OR-SELECT
    ;     (CLSS:SELECT STRING LQUERY::ROOT)
    ; 
    ; note: deleting unreachable code
    ; 
    ; caught WARNING:
    ;   Derived type of STRING is (VALUES STRING &OPTIONAL), conflicting with its asserted type LIST.
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"

More log detail here: http://report.quicklisp.org/2015-01-10/failure-report/lquery.html

**Comment by Shinmera** [comment]
This is in consequence of a bad type declaration in CLSS that was fixed last night Shinmera/CLSS#2. It should build properly if you fetch the latest CLSS sources (at least, I can't reproduce the error with all sources updated).
