### ISSUE TITLE
lquery leaks/blocks memory?

### ISSUE THREAD

**Issue by MatthewRock** [Shinmera/lquery#3]
Now I'm unable to prove as for what causes it, but I'm thinking that lquery might be causing it.

Here's my code:
`````
(defun string-remove-whitespace (str)
  (string-trim '(#\Space #\Newline #\Backspace #\Tab #\Linefeed #\Page #\Return #\Rubout) str))

(defun get-all-texts (starting-directory
                      &aux (target-file #P"~/output.txt"))
  (loop for file in ;every .xml file in the starting-directory
       (remove-if-not (lambda (x) (cl-ppcre:scan ".*\\.xml" (namestring x)))
                      (uiop:directory-files starting-directory))
       do (save-text-to-file target-file (get-text-from-file file)))
  (loop for directory in (uiop:subdirectories starting-directory)
       do (get-all-texts directory)))

(defun get-text-from-file (file)
  (let* ((text
          (coerce
           (map 'vector
                #'string-remove-whitespace
                (lquery:$ (initialize file) "s" (text)))
           'list))
         (len (length text)))
    (if (< len 10) (return-from get-text-from-file nil))
    (setf text (subseq text 0 (- len 7)))
    (prepare-good-text text)))

(defun save-text-to-file (file text-list)
  (with-open-file (outfile file :direction :output :if-exists :append
                           :if-does-not-exist :create)
    (format outfile "~{~A☯~%~}" text-list))) ;char-code of separator: 9775

(defun prepare-good-text (text-list)
  (mapcar
   (lambda (x)
     (cl-ppcre:regex-replace-all
      "\\s+(?=[,\\.\\;\\:\\!\\?])"
      (cl-ppcre:regex-replace-all
       "\\s+"
       (cl-ppcre:regex-replace-all
        "\\n" x "") " ") "")) text-list))
`````

Now this was used to parse a big corpora(~67GB) of many xml files that aren't big(~.2-1MB). What it does is: go to each xml file in the directory tree, parse it, extract data that's interesting, use cl-ppcre to format it, save to file. Now after some long time(~3-4GB of extracted data), I get heap exhausted error, which looked something like this:

`Heap exhausted during allocation: 64290816 bytes available, 67108896 requested.`

Now if you think it's unlikely that it's caused by lquery, than it's okay. If you want me to provide more info, I can run the script, but it will take some time for me to get output(as I said - script works ~1GB/1.5h, so it would take 4-6hours to get to an error). Error wasn't permanent - i could select restart to retry, and it continued to work, but it was blocking my workflow.

I think that it's because of lquery, because I saw some calls to lquery/plump in call stack. I think my function is unlikely to cause the problem, because it takes 1 frame for each directory depth(and I guess that it's not deeper than 10), and lists that are kept for each call aren't big either(maximum for subdirectories would be ~300 directories), so I'd estimate upper bound for lists as 73kb.  If you need more info or if I was unclear, please let me know.

edit: Actually I was able to find (shortened) call stack:
`````
        ("Heap exhausted (no more space for allocation).\n4128768 bytes available, 33554464 requested.\n\nPROCEED WITH CAUTION." "   [Condition of type SB-KERNEL::HEAP-EXHAUSTED-ERROR]" nil)
        (("RETRY" "Retry SLIME REPL evaluation request.")
         ("*ABORT" "Return to SLIME's top level.")
         ("ABORT" "abort thread (#<THREAD \"new-repl-thread\" RUNNING {100A2774B3}>)"))
        ((0 "(SB-KERNEL::HEAP-EXHAUSTED-ERROR 2064384 16777232)")
         (1 "(\"foreign function: call_into_lisp\")")
         (2 "(\"foreign function: funcall2\")")
         (3 "(\"foreign function: gc_heap_exhausted_error_or_lose\")")
         (4 "(\"foreign function: gc_find_freeish_pages\")")
         (5 "(\"foreign function: gc_alloc_large\")")
         (6 "(\"foreign function: alloc\")")
         (7 "(\"foreign function: alloc_tramp\")")
         (8 "(SB-IMPL::STRING-OUTPUT-STREAM-NEW-BUFFER :INVALID-VALUE-FOR-UNESCAPED-REGISTER-STORAGE :INVALID-VALUE-FOR-UNESCAPED-REGISTER-STORAGE)")
         (9 "(SB-IMPL::STRING-SOUT #<SB-IMPL::STRING-OUTPUT-STREAM {101FACBE13}> \"          43</w> ..)")
         (10 "(SB-IMPL::%WRITE-STRING \"          43</w> ..)")
         (11 "(SB-IMPL::ANSI-STREAM-WRITE-SEQUENCE \"          43</w> ..)")
         (12 "(WRITE-SEQUENCE \"          43</w> ..)")
         (13 "(PLUMP-PARSER:SLURP-STREAM #<SB-SYS:FD-STREAM for \"file /home/malice/kck/opensubtitles/OpenSubtitles2011/xml/pl/2008/37086/3394751_1of1.xml\" {101FACB323}>)"
             (:restartable t))
         (14 "((:METHOD PLUMP-PARSER:PARSE (STREAM)) #<SB-SYS:FD-STREAM for \"file /home/malice/kck/opensubtitles/OpenSubtitles2011/xml/pl/2008/37086/3394751_1of1.xml\" {101FACB323}> :ROOT NIL) [fast-method]"
             (:restartable t))
         (15 "((:METHOD PLUMP-PARSER:PARSE (PATHNAME)) #P\"/home/malice/kck/opensubtitles/OpenSubtitles2011/xml/pl/2008/37086/3394751_1of1.xml\" :ROOT NIL) [fast-method]"
             (:restartable t))
         (16 "(LQUERY-FUNCS:INITIALIZE NIL #P\"/home/malice/kck/opensubtitles/OpenSubtitles2011/xml/pl/2008/37086/3394751_1of1.xml\")"
             (:restartable t))
         (17 "(GET-TEXT-FROM-FILE #P\"/home/malice/kck/opensubtitles/OpenSubtitles2011/xml/pl/2008/37086/3394751_1of1.xml\")"
             (:restartable t))
         (18 "(GET-ALL-TEXTS #P\"/home/malice/kck/opensubtitles/OpenSubtitles2011/xml/pl/2008/37086/\")"
             (:restartable t))
         (19 "(GET-ALL-TEXTS #P\"/home/malice/kck/opensubtitles/OpenSubtitles2011/xml/pl/2008/\")"
             (:restartable t)))
        (381))
`````

**Comment by Shinmera** [comment]
That lQuery and Plump are in the call stack doesn't really mean much of anything. The more likely cause here is that there's too much stuff being allocated too quickly and SBCL doesn't GC it all up. All of your functions create new copies of strings many times over. Thus you create lots and lots of tiny pieces of garbage.

If it truly were a memory retention issue then there would have to be live references to the data somewhere, and those would not show up in the stack. The only reference that lQuery keeps implicitly is `lquery:*lquery-master-document*`, however since this is only ever a singular reference, I doubt that this could be the cause.

What you can do to maybe help your issue is to throw in an `(sb-ext:gc)` for each file you process. This will cause SBCL to run a garbage collection run explicitly and might cause it to collect before it runs out of memory. Alternatively you can also increase SBCL's heap by using the `--dynamic-space-size` command line argument.

Another thing worth trying is to simply run your functions on the file it failed on and on the file prior to that. Perchance their in-memory representation together is enough to blow the heap on its own.
