### ISSUE TITLE
Question about combining queries

### ISSUE THREAD

**Issue by jephthai** [Shinmera/lquery#5]
I don't have an issue, per se, just a question about usage.  I really like the library -- it installed painlessly and I was up and running right away.  

In my scenario, I'm building a web scraper.  In a web page's source, I need to find the `img` tag that has a certain class, extract its `src` attribute, and use that URL for later processing.  I've tried a number of permutations, and can't seem to figure out if it's possible to do all of that in one call.  Instead, I end up using `lquery` to pull out all the `img` tags, and then post-process to figure out which ones have the right `class` value.  Something like this:

    (defun find-media (images)
      "Given list of <IMG> tags, find which has class 'media'"
      (loop 
         for image across images
         for class = (aref ($ image (attr "class")) 0)
         when (string= class "media")
         collect image))
    
    (defun get-media-url (url)
      "Find last <IMG> tag with target class value"
      (let* ((source (drakma:http-request url))
             (images ($ (initialize source) "img"))
             (media  (find-media images)))
        (car (reverse (coerce ($ media (attr "src")) 'list)))))

I see the `filter` function referenced in the docs, but no examples using it, and I'm confused how it might be applied.  Is there a way to filter by attribute values and then extract attributes more quickly?

Thanks for any help!  Love the library!

-Josh Stone-

**Comment by Shinmera** [comment]
A regular string anywhere within the chain will act as a CSS selector that finds the appropriate elements from the current set. [Supported are](http://shinmera.github.io/CLSS/) full CSS Level3 selectors (except for a few that don't make sense outside a browser). Also see Here's an example for that:

    ($ (initialize (drakma:http-request url)) "img.media" (attr :src))

You can also use the `map` lquery-function to call a function for each src attribute like so:

    ($ (initialize (drakma:http-request url)) "img.media" (attr :src) (map #'print))

**Comment by jephthai** [comment]
Cool, that works great.  I didn't realize I could just append CSS styles like that.  Thanks!
