### ISSUE TITLE
lquery::classes is broken since the merge of cl:member and clss::split

### ISSUE THREAD

**Issue by desiderius** [Shinmera/lquery#8]
Hello, the unit tests fails since the merge of https://github.com/Shinmera/CLSS/pull/7/commits/5d1b7c9dff67e333b83fe6339eb015ce2e730642.
The removed `clss::split` function is used in `lquery::classes`, see https://github.com/Shinmera/lquery/blob/205fa1fc8ab9c75faba27c7debdd0001fa928917/toolkit.lisp#L132

The semantic is different between the two versions so I am not confident enough to submit a patch.

**Comment by Shinmera** [comment]
Thanks for the report!

**Comment by desiderius** [comment]
That was fast :laughing:, thank you.
