### ISSUE TITLE
`(text)` doesn't trim surrounding white spaces

### ISSUE THREAD

**Issue by fukamachi** [Shinmera/lquery#9]
`lquery-funcs:text` returns the content including surrounding white spaces.

```common-lisp
(lquery:$ (initialize "<html><body><p id='main'> abc def  </p></body></html>")
  "#main"
  (text))
;=> #(" abc def  ")

;; 'html' returns the same
(lquery:$ (initialize "<html><body><p id='main'> abc def  </p></body></html>")
  "#main"
  (html))
;=> #(" abc def  ")
```

Is this behavior intended?
In JavaScript, `.innerText` trims them, though `.innerHTML` doesn't.

```javascript
document.getElementById('main').innerText
//=> "abc def"

document.getElementById('main').innerHTML
//=> " abc def  "
```

I assume that it couldn't always be easy, as a white space can be contained by `&nbsp;`, however, I don't really want to trim all white spaces manually for every scraped HTML.

**Comment by Shinmera** [comment]
lQuery is primarily modelled after jQuery. jQuery's documentation for the [text function](http://api.jquery.com/text/) mentions this:

> Due to variations in the HTML parsers in different browsers, the text returned may vary in newlines and other white space.

If we look at what MDN says about [innerText](https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText) it seems rather ambiguous what it really means for the text to be returned as "rendered".

To me it is the more sensible and unsurprising behaviour not to do any text wrangling, and would thus prefer to keep the current behaviour instead of breaking compatibility. A case could be made to include a new operator (`rendered-text` perhaps?) that behaves more akin to `innerText`.

As for `&nbsp;`, Plump parses all entities to raw text and the DOM has no knowledge of what was encoded raw or as an entity. There is thus no way for lQuery to know whether something was `&nbsp;` or a regular space.

**Comment by fukamachi** [comment]
> A case could be made to include a new operator (rendered-text perhaps?) that behaves more akin to innerText.

That sounds okay and sufficiently helpful to me.
I don't think that lQuery should be compatible with jQuery or vanilla JavaScript, so I leave the decision up to you.

**Comment by Shinmera** [comment]
I can do this, but I'm not so sure what the exact behaviour of the operator should be. Consider the following cases:

1. `<a>_1_</a>` Should this be `_1_` or `1`?
2. `<a>1__2</a>` Should this be `1__2` or `1_2`?
3. `<a>1_<b>2</b></a>` Should this be `1_2` or `12`?
4. `<a>1_<b>_2</b></a>` Should this be `1__2` or `1_2` or `12`?

I had to use an underscore in place of the spaces as it was, ironically enough, trimming and deduplicating them. Anyway, an argument can be made for any of these choices, depending on what you consider to be the "rendered" representation.

**Comment by fukamachi** [comment]
In my use case, these are steps to make a "rendered" representation I expect.

1. Concatenates all `(text)` into a string
2. Remove surrounding white spaces (including tabs and newlines)
3. Replace all serial white spaces into a single white space

With this spec, those examples are:

1. `<a>_1_</a>` -> `1`
2. `<a>1__2</a> -> `1_2`
3. `<a>1_<b>2</b></a>` -> `1_2`
4. `<a>1_<b>_2</b></a>` -> `1_2`

**Comment by Shinmera** [comment]
So for instance TAB should be replaced with a Space? Should all whitespace be coerced into just spaces, then? If so, what whitespace? Everything from Unicode with WSpace=Y, or only TAB, CR, and LF?

**Comment by fukamachi** [comment]
> TAB should be replaced with a Space?

Right. All sequences of white spaces (longer than 1) including tabs and
newlines are collapsed to a single ASCII space.

**Comment by Shinmera** [comment]
*any* white space in the Unicode sense, or just ASCII white space?

**Comment by fukamachi** [comment]
That would be a point to argue, though I don’t have a strong opinion about
it.
When talking about what can be felt natural to me, collapsing only ASCII
spaces is natural and not surprising.
Japanese full-width “ “ is literally a space but it haven’t been cared
conventionally.

**Comment by Shinmera** [comment]
Please update Plump and lQuery to master and confirm that the new `render-text` function behaves as required.

**Comment by fukamachi** [comment]
Thanks for your quick response!

However, it seems that the behavior is a little bit different from that I expected.

```common-lisp
;; 1__2 -> 1_2
(lquery:$ (initialize "<html><body><p id='main'><a>1  2</a></p></body></html>")
  "#main"
  (render-text))
;=> "12"
```

I assume a sequence of white spaces between elements will be converted into a single space. (`"1_2"` for the above example)

**Comment by Shinmera** [comment]
I thought I could be nice and tidy by using `map`. Fixed now.

**Comment by fukamachi** [comment]
Now works perfectly! Thanks a lot :)
